### ISSUE TITLE
Claimed repo appearing under scaladex-void

### ISSUE THREAD

**Issue by pepegar** [scalacenter/scaladex-contrib#34]
Hi!

I've previously claimed http://github.com/pepegar/hammock , but it's still appearing under scaladex-void in index.scala-lang.org.

Evidence:

https://github.com/scalacenter/scaladex-contrib/blob/master/claims.json#L800-L801

Is there anything else I should do for making it appear correctly?

Thank you very much for your work in Scaladex, awesome stuff!

**Comment by MasseGuillaume** [comment]
Looks ok now: https://index.scala-lang.org/pepegar/hammock/hammock-core/0.8.5?target=_2.12
