### ISSUE TITLE
netflix oss

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scaladex-contrib#9]
@brharrington
@coryb
@aspyker

Hi guys, 
I'm working on the [Scala Index](https://index.scala-lang.org). We automatically build a catalogue of open source scala libraries, projects and frameworks. We search for releases on Maven Central and on Bintray.

[Netflix](https://index.scala-lang.org/netflix) currently has one project [iep-shadow](https://index.scala-lang.org/netflix/iep-shadow)

I saw that you also have Atlas, Edda and Osstracker. 

However you guys dont use the sbt convention of attaching the scala version to the artifactId. This is alright, the only downside is that you are not indexed automatically.

Our solution require updating https://github.com/scalacenter/scaladex-data/blob/master/non-standard.json manually.

For example 

``` json
{
  "com.netflix.atlas atlas-core": "pom"
}
```

would add atlas-core to the index

**Comment by brharrington** [comment]
For Atlas and Edda we typically use them as end applications so we haven't worried too much about cross-building. However, if it is more convenient for other uses we can add the scala version in to the artifact ids. I would rather not keep up with a manually updated file.

I filed https://github.com/Netflix/atlas/issues/401 to track.

@aspyker would need to comment on osstracker.

**Comment by MasseGuillaume** [comment]
@brharrington 
atlas in now on the front page under Recent Projects :+1: 
https://index.scala-lang.org/

**Comment by brharrington** [comment]
Great. Edda uses a gradle build so I'll need to look at that a little bit more to figure out how to make it work.
